---
title: "Prepare data"
format: html
---

```{r}
#| label: setup
#| include: false

library(tidyverse)
theme_set(theme_light())
library(countrycode)
library(glottologR)
library(WDI)
```

```{r}
#| label: BII

BII <- readRDS("raw/BII/long_data.rds") |> 
  filter(year == 2020, variable == "bii") |> 
  mutate(
    iso3c = str_extract(area_code, "[A-Z]{3}"),
    country = countrycode(iso3c, "iso3c", "country.name.en"),
    iso2c = countrycode(iso3c, "iso3c", "iso2c"),
    BII = value,
    # Adjust BII when 1 to apply qlogis later.
    BII_adj = ifelse(BII == 1, BII - 0.01, BII),
    BII_logit = qlogis(BII_adj)
  )
```

```{r}
#| label: BII-countries-mean

BII_countries_mean <- BII |> 
  summarise(
    BII_mean = mean(BII),
    BII_logit_mean = mean(BII_logit),
    BII_logit_se = sd(BII_logit) / sqrt(n()),
    .by = c(iso3c, iso2c, country)
  ) |>
  arrange(country)

write_csv(BII_countries_mean, "derived/BII-countries-mean.csv")
```

```{r}
#| label: nlangs

data("glot_aes")

ling_countries <- glot_aes |> 
  separate_longer_delim(Countries, ";") |> 
  filter(Value != "extinct") |> 
  mutate(
    country = countrycode(Countries, "iso2c", "country.name.en"),
    iso2c = Countries,
    iso3c = countrycode(Countries, "iso2c", "iso3c"),
    endanger_severity = as.numeric(Value) / 6,
  ) |> 
  group_by(iso3c, iso2c, country) |>
  summarise(
    n_langs = n(),
    n_langs_log = log(n_langs),
    EI = mean(endanger_severity),
    EI_logit = qlogis(EI),
    .groups = "drop"
  )
```

```{r}
#| label: wdi

iso2_list <- unique(codelist$iso2c)
iso2_list <- iso2_list[!is.na(iso2_list)]

country_wdi <- WDI(indicator = c("AG.SRF.TOTL.K2", "SP.POP.TOTL"), start = 2020, end = 2020, country = iso2_list)
```

```{r}
#| label: bioling

bioling <- left_join(BII_countries_mean, ling_countries) |> 
  left_join(y = country_wdi) |> 
  mutate(
    area_log = log(AG.SRF.TOTL.K2),
    pop_log = log(SP.POP.TOTL)
  ) |> 
  as_tibble()

write_csv(bioling, "derived/bioling.csv")

usethis::use_data(bioling, overwrite = TRUE)
```

